post for young book
readchina/readchina.github.io pull request #281
Opened 2023-05-04 09:15 UTC by damianodamiani

please check -- merging only after May 9!

2023-05-04 10:17 UTC, LenaHenningsen requested changes
Lovely; can you change to as a FORMER member of the German Young Academy.

Again I cannot build it, but text and image are fine.

2023-05-05 14:21 UTC, damianodamiani commented
> Lovely; can you change to as a FORMER member of the German Young Academy.
> 
> Again I cannot build it, but text and image are fine.

done, please merge at will @whalekeykeeper -- because the post wont appear until 10.05, correct?

2023-05-06 06:21 UTC, whalekeykeeper commented
> 

yes, it should be.

2023-05-06 06:25 UTC, whalekeykeeper approved these changes

2023-05-06 06:32 UTC, merged